### ISSUE TITLE
PyEZ not working with build 11.4X12.2

### ISSUE THREAD

**Issue by jamesboswell** [Juniper/py-junos-eznc#463]
Python 2.7.9 with  `junos-eznc==1.2.3`

Device.open() fails on MX960 routers running 11.4X12.1 or .2,  special/internal build to address various PRs.   This appears to be very similar to issue https://github.com/Juniper/py-junos-eznc/issues/115

``` 
dev = Device('<removed>', user='<removed>', password='<removed>')
 dev.open()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jnpr/junos/device.py", line 495, in open
    self.facts_refresh()
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jnpr/junos/device.py", line 773, in facts_refresh
    gather(self, self._facts)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jnpr/junos/facts/swver.py", line 195, in facts_software_version
    facts['version_info'] = version_info(facts['version'])
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jnpr/junos/facts/swver.py", line 19, in __init__
    [int(xm.group(1)), xm.group(2), int(xm.group(3))])
AttributeError: 'NoneType' object has no attribute 'group'
```
 
```
--- JUNOS 11.4X12.2 built 2014-03-27 19:18:01 UTC
```

No issues with  `--- JUNOS 11.4R5.7 built 2013-01-05 14:40:22 UTC`, on an MX80 validating my local install of PyEZ does work

**Comment by jamesboswell** [comment]
Submitted fix in pull request:  https://github.com/Juniper/py-junos-eznc/pull/464
